default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: nyc_development

test:
  <<: *default
  database: nyc_test

production:
  <<: *default
  database: nyc_production
