Venue.create!({ name: "The Bowery Ballroom", address: "6 Delancey St, New York, NY 10002", slug: "bowery-ballroom" })
Venue.create!({ name: "C'mon Everybody", address: "325 Franklin Ave, Brooklyn, NY 11238", slug: "cmon-everybody" })
Venue.create!({ name: "Baby's All Right", address: "146 Broadway, Brooklyn, NY 11211", slug: "babys-all-right" })
Venue.create!({ name: "Rough Trade NYC", address: "64 N 9th St, Brooklyn, NY 11249", slug: "rough-trade" })
Venue.create!({ name: "Brooklyn Bowl", address: "61 Wythe Ave, Brooklyn, NY 11249", slug: "brooklyn-bowl" })
Venue.create!({ name: "Mercury Lounge", address: "217 E Houston St, New York, NY 10002", slug: "mercury-lounge" })
Venue.create!({ name: "Pianos", address: "158 Ludlow St, New York, NY 10002", slug: "pianos" })
Venue.create!({ name: "Music Hall of Williamsburg", address: "66 N 6th St, Brooklyn, NY 11211", slug: "music-hall-of-williamsburg" })
Venue.create!({ name: "Terminal 5", address: "610 W 56th St, New York, NY 10019", slug: "terminal-5" })
Venue.create!({ name: "Brooklyn Mirage", address: "140 Stewart Ave, Brooklyn, NY 11237", slug: "brooklyn-mirage" })
Venue.create!({ name: "Brooklyn Steel", address: "319 Frost St, Brooklyn, NY 11222", slug: "brooklyn-steel" })
Venue.create!({ name: "Output", address: "74 Wythe Ave, Brooklyn, NY 11249", slug: "output" })
Venue.create!({ name: "Brooklyn Hangar", address: "2 52nd St, Brooklyn, NY 11232", slug: "brooklyn-hangar" })
Venue.create!({ name: "Playstation Theater", address: "1515 Broadway, New York, NY 10036", slug: "playstation-theater" })
Venue.create!({ name: "Barclays Center", address: "620 Atlantic Ave, Brooklyn, NY 11217", slug: "barclays-center" })
Venue.create!({ name: "Madison Square Garden", address: "4 Pennsylvania Plaza, New York, NY 10001", slug: "madison-square-garden" })
Venue.create!({ name: "House of Yes", address: "2 Wyckoff Ave, Brooklyn, NY 11237", slug: "house-of-yes" })
Venue.create!({ name: "Schimanski", address: "54 N 11th St, Brooklyn, NY 11249", slug: "schimanski" })

Venue.create!({ name: "", address: "", slug: "" })
Venue.create!({ name: "", address: "", slug: "" })
Venue.create!({ name: "", address: "", slug: "" })
Venue.create!({ name: "", address: "", slug: "" })
Venue.create!({ name: "", address: "", slug: "" })
Venue.create!({ name: "", address: "", slug: "" })
Venue.create!({ name: "", address: "", slug: "" })
Venue.create!({ name: "", address: "", slug: "" })
Venue.create!({ name: "", address: "", slug: "" })
Venue.create!({ name: "", address: "", slug: "" })
Venue.create!({ name: "", address: "", slug: "" })
Venue.create!({ name: "", address: "", slug: "" })
Venue.create!({ name: "", address: "", slug: "" })
